apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: apollo
  labels:
    app: apollo-{{ .Release.Namespace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  type: NodePort
  selector:
    app: apollo-{{ .Release.Namespace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  ports:
  - name: apollo
    port: 28898
    protocol: TCP
  
